# Generated by Django 5.1.2 on 2024-11-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Freelancer', 'Freelancer'), ('Client', 'Client')], default='User', max_length=10),
        ),
    ]
