# Generated by Django 5.1.2 on 2024-10-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field', models.CharField(choices=[('Transport', 'Transport'), ('Agriculture', 'Agriculture'), ('Trade', 'Trade'), ('Environmental Protection', 'Environmental Protection')], max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('budget', models.IntegerField()),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
